// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _22Percent_BE.Data;

#nullable disable

namespace _22Percent_BE.Migrations
{
    [DbContext(typeof(_22Context))]
    [Migration("20231021143745_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("_22Percent_BE.Data.Entities.DetailImportInvoice", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("importInvoiceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ingredientId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<double>("weight")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.HasIndex("importInvoiceId");

                    b.HasIndex("ingredientId");

                    b.ToTable("DetailImportInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.DetailProduct", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ingredientID")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("ingredientID");

                    b.HasIndex("productId");

                    b.ToTable("DetailProducts");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.DetailSaleInvoice", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("productId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.Property<string>("saleInvoiceId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.HasIndex("saleInvoiceId");

                    b.ToTable("DetailSaleInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Ingredient", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("importPrice")
                        .HasColumnType("double");

                    b.Property<double>("loss")
                        .HasColumnType("double");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("netWeight")
                        .HasColumnType("double");

                    b.Property<double>("realWeight")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Invoices.SubInvoices.ImportInvoices", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("ImportInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Invoices.SubInvoices.PaymentInvoices", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("descriptions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("PaymentInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Invoices.SubInvoices.SaleInvoices", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("createUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("discount")
                        .HasColumnType("double");

                    b.Property<double>("quantity")
                        .HasColumnType("double");

                    b.Property<double>("total")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("SaleInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Product", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<double>("cost")
                        .HasColumnType("double");

                    b.Property<string>("createUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.User", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("createUser")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.DetailImportInvoice", b =>
                {
                    b.HasOne("_22Percent_BE.Data.Entities.Invoices.SubInvoices.ImportInvoices", "importInvoices")
                        .WithMany("detailImportInvoices")
                        .HasForeignKey("importInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_22Percent_BE.Data.Entities.Ingredient", "ingredient")
                        .WithMany("detailImportInvoices")
                        .HasForeignKey("ingredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("importInvoices");

                    b.Navigation("ingredient");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.DetailProduct", b =>
                {
                    b.HasOne("_22Percent_BE.Data.Entities.Ingredient", "ingredient")
                        .WithMany("detailProducts")
                        .HasForeignKey("ingredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_22Percent_BE.Data.Entities.Product", "product")
                        .WithMany("detailProducts")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ingredient");

                    b.Navigation("product");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.DetailSaleInvoice", b =>
                {
                    b.HasOne("_22Percent_BE.Data.Entities.Product", "product")
                        .WithMany("detailSaleInvoices")
                        .HasForeignKey("productId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_22Percent_BE.Data.Entities.Invoices.SubInvoices.SaleInvoices", "saleInvoices")
                        .WithMany("detailSaleInvoices")
                        .HasForeignKey("saleInvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");

                    b.Navigation("saleInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Ingredient", b =>
                {
                    b.Navigation("detailImportInvoices");

                    b.Navigation("detailProducts");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Invoices.SubInvoices.ImportInvoices", b =>
                {
                    b.Navigation("detailImportInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Invoices.SubInvoices.SaleInvoices", b =>
                {
                    b.Navigation("detailSaleInvoices");
                });

            modelBuilder.Entity("_22Percent_BE.Data.Entities.Product", b =>
                {
                    b.Navigation("detailProducts");

                    b.Navigation("detailSaleInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
